apiVersion: v1
kind: Service
metadata:
  name: sentrydash-backend
  namespace: sentrydash
spec:
  selector:
    app: sentrydash-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
