apiVersion: v1
kind: Service
metadata:
  name: sentrydash-frontend
  namespace: sentrydash
spec:
  type: ClusterIP
  selector:
    app: sentrydash-frontend
  ports:
    - port: 80
      targetPort: 80
