apiVersion: v1
kind: Secret
metadata:
  name: sentrydash-secrets
  namespace: sentrydash
type: Opaque
stringData:
  APPINSIGHTS_CONNECTION_STRING: "InstrumentationKey=b36210b2-5c94-46d9-99c6-6197457f1da2;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=c75fa98f-4770-4ca6-8c08-70a8ce231dd6"
  COSMOS_ENDPOINT: "https://sentrydash-cosmos-db.documents.azure.com:443/"
  COSMOS_KEY: "OziUhNyBXd1PrAPHdycfCID5pf04rl0viOYwFS3BBExJJHzH2CiKM7Kjh56eb3UWfP1bF4SOAgPBACDbiIeZvg=="