apiVersion: v1
kind: ConfigMap
metadata:
  name: sentrydash-config
  namespace: sentrydash
data:
  NODE_ENV: "production"
  # this is used by apps if needed (example)
  API_BASE_INTERNAL: "http://sentrydash-backend:3000"
